name: Fullness of Christ
description: Until we all attain to the unity of the faith, and of the knowledge of the Son of God, to a mature man, to the measure of the stature which belongs to the fullness of Christ.
url: http://fullnessofchrist.com
markdown: redcarpet
pygments: true
timezone: US/Central
